ChainSafe/js-libp2p-gossipsub

package-lock.json
package.json

The directory structure is outdated. I have changed it to make it much simpler and easier to add to in the future. Initially, I will be coding up all gossip sub functionality in index.js. If needed, we can later refactor into more files and changes the repo structure.

Changed repo structure

---

src/heartbeat.js
src/pubsub.js

In the context of integrating `gossipsub` into `js-libp2p` [libp2p/js-libp2p#365](https://github.com/libp2p/js-libp2p/pull/365), some problems appeared and this PR addresses them.

fix: integration with js-libp2p

---

package.json

The release tooling, using `aegir release` automatically bumps the version.
If we reset to v0.0.0, aegir can bump us to v0.0.1

Reset to v0.0.0

---

src/pubsub.js
test/gossip.js
test/pubsub.spec.js

BREAKING CHANGE: Older pubsub peers that do not sign messages will have their messages dropped and not forwarded. Gossipsub peers are unaffected, as message signing has been enabled since the initial release.
This adds signature verification that was introduced in the latest pubsub version https://github.com/libp2p/js-libp2p-pubsub/pull/20.

feat: add signature verification

---

src/pubsub.js
test/2-nodes.js

When we send a subscribe or unsubscribe message, we needed to wait for a while in order to guarantee that peers are properly connected. 
This way, we had no precise metrics of when to "believe" that the dial was finished and the peer properly handled by the pubsub protocol. 
In this PR, I added a function to guarantee that when we want to send SUBSCRIBE or UNSUBSCRIBE messages, we wait for peers which are still establishing a stream communication with the peer. I had problems with this when integrating `gossipsub` with `js-ipfs`, as we connect to all the bootstrap peers, and if we start using the pubsub api, we will not be able to write to peers, which are still being connected.

fix: send subscriptions once ready

---

src/heartbeat.js

The heartbeat code sets a timeout to start the heartbeat then sets an interval to perform the heartbeat.
If the node is shut down after the timeout is set but before it fires, the interval is set and the process never ends.
This PR refactors the heatbeat shutdown to clear the timeout as well as the interval.

fix: fix heartbeat startup/shutdown timing bug

---

README.md

This project is not Aegir, this updates the travis link in the README to point to the right build

docs: fix travis link

---

src/pubsub.js
test/floodsub.spec.js

The tests of this module are currently failing but they don't fail the build because the error that should fail it is thrown [out of the flow control](https://github.com/ChainSafe/gossipsub-js/blob/master/test/floodsub.spec.js#L21) of the tests.  An [UnhandledPromiseRejectionWarning](https://travis-ci.com/ChainSafe/gossipsub-js/jobs/278427804#L270) is thrown.
This PR:
1. Passes an `error` object to `done` if the error condition is hit
2. Fixes a bug where a message was being sent back to the sender and then emitted by the sender even though `emitSelf` was false
3. Where multiple messages are published in a test, make each message different so we can assert that they were all actually sent/received

fix: fix double publish bug

---

src/index.js
src/pubsub.js

I'm trying to remove use of the node `assert` module from our stack as it's causing problems - the polyfill is big, we can simulate it by throwing an Error and it doesn't work under React Native.

fix: remove use of assert module

---

README.md
src/index.js
src/messageCache.js
src/pubsub.js
test/messageCache.spec.js

+ Lodestar/eth2 wants a way to specify its own `msgId()` function 
+ The change should be backward compatible
+ Have default message id function calculated as earlier
+ Provide a way to override that as opttions
+ This is inspired by https://github.com/libp2p/go-libp2p-pubsub/pull/248/files

Provide a way to override message id function

---

package.json
src/index.d.ts
tsconfig.json

resolves #50 
Types are migrated from https://github.com/ChainSafe/libp2p-ts *
* removed `message-id` as it's not specified in spec or in proto file

add typescript definitions

---

README.md

This PR specifies the spec version implemented on the module, so that it is clear for the users.
Closes #68

docs: specify spec version implemented

---

package.json
src/pubsub.js
test/2-nodes.spec.js
test/emit-self.spec.js
test/floodsub.spec.js
test/gossip-incoming.spec.js
test/gossip.js
test/messageCache.spec.js
test/multiple-nodes.spec.js
test/pubsub.spec.js

Related to https://github.com/ipfs/js-ipfs/issues/2924

fix: add buffer and update deps

---

package.json
test/2-nodes.spec.js
test/floodsub.spec.js
test/gossip.js
test/mesh.spec.js
test/multiple-nodes.spec.js
test/pubsub.spec.js
test/utils/index.js

This PR makes libp2p pubsub subsystem use unidirectional streams instead of bidirectional streams per discussion on [ipfs/go-ipfs#7390](https://github.com/ipfs/go-ipfs/issues/7390).
More details about the reasoning for this can be found in https://discuss.libp2p.io/t/gossip-questions/257/6
This PR replicates #105 for the `0.3.x` version range of `libp2p-gossipsub`
I have tested this change on all libp2p repos: `js-libp2p`, `libp2p-daemon` and `interop` and everything is working properly. The tests here need to be updated though, as a result of the tests being implemented considering a bidirectional stream.
Bear in mind that a lot of this "connection logic" can be abstracted. I did not worry about it and just followed what we already had in floodsub and gossipsub. Hopefully, after …

fix: use unidirectional streams v0.3.x

---

package.json
test/2-nodes.spec.js
test/floodsub.spec.js
test/gossip.js
test/mesh.spec.js
test/multiple-nodes.spec.js
test/pubsub.spec.js
test/utils/index.js

This PR makes libp2p pubsub subsystem use unidirectional streams instead of bidirectional streams per discussion on [ipfs/go-ipfs#7390](https://github.com/ipfs/go-ipfs/issues/7390).
More details about the reasoning for this can be found in https://discuss.libp2p.io/t/gossip-questions/257/6
I have tested this change on all libp2p repos: `js-libp2p`, `libp2p-daemon` and `interop` and everything is working properly. The tests here need to be updated though, as a result of the tests being implemented considering a bidirectional stream.
Bear in mind that a lot of this "connection logic" can be abstracted. I did not worry about it and just followed what we already had in floodsub and gossipsub. Hopefully, after `gossipsub@1.1`, I want to create the libp2p pubsub interface and move/refactor the …

fix: use unidirectional streams

---

test/gossip-incoming.spec.js
test/gossip.js
test/mesh.spec.js
test/multiple-nodes.spec.js
ts/constants.ts
ts/getGossipPeers.ts
ts/index.ts

Add new gossipsub constants as well as comments for existing constants
A future PR will change how the gossipsub multicodecs are handled (eg: filtering peers by the gossipsub v1.1 multicodec instead of the gossipsub v1.0 multicodec)

gs1.1 constants and comments

---

package.json
test/2-nodes.spec.js
test/emit-self.spec.js
test/floodsub.spec.js
test/heartbeat.spec.js
test/pubsub.spec.js
test/utils/index.js
ts/index.ts
ts/score/peerScore.ts

Building off #83 
Minimal integration of peer score
- adds a PeerScore object to gossipsub
- plugs into gossipsub `start`/`stop`/`_addPeer`/`_removePeer`
- pass a ConnectionManager into the constructor of gossipsub
- update tests to new constructor

gs1.1 Integrate peer score

---

ts/getGossipPeers.ts

Update `getGossipPeers` to suit gs 1.1 needs
- add `filter` param - filter peers before shuffling, will be used to filter peers by score, mesh inclusion, etc
- add gossipsub v1.1 protocol check - filter peers by gossipsub v1.0 and gossipsub v1.1 protocol strings

gs1.1 update get gossip peers

---

ts/getGossipPeers.ts
ts/index.ts

Builds off #87 
Implements https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#flood-publishing
Add `floodPublish` option, defaulted to true
With flood publishing on:
Self-published messages should be sent to all peers with scores above the publish threshold
With flood publishing off:
Self-published messages should be sent using gossipsub 1.0 functionality

gs1.1 flood publishing

---

test/gossip.js
ts/heartbeat.ts
ts/index.ts
ts/score/peerScore.ts

Implements
https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#outbound-mesh-quotas
https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#heartbeat-maintenance
https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#spam-protection-measures `GRAFT` spam protection
Most of these edits made directly in line with the go-libp2p-pubsub impl. https://github.com/libp2p/go-libp2p-pubsub/blob/master/gossipsub.go
I tried to avoid rewriting / adding all features, so there are some conditionals/blocks that aren't yet included (eg: direct peers, graft/prune backoff tracking, px, etc)
Big updates:
`_addPeer`, `_removePeer`
- add/remove `outbound` cache for peer
`_handleGraft`
- update to ignore negative score peer grafts
- only …

gs1.1 outbound mesh quota

---

ts/getGossipPeers.ts
ts/heartbeat.ts
ts/index.ts
ts/utils/hasGossipProtocol.ts
ts/utils/index.ts

Implements https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#adaptive-gossip-dissemination
- Closely follows the go-libp2p-pubsub implementation
- Adaptive gossip dissemination in `_emitGossip`
- fixes up the fanout peer handling in `heartbeat`
- includes bugfix in the heartbeat where we were deleting fanout peers who _are_ still in the topic (yikes)
- Add `hasGossipProtocol` utility function, replace where appropriate

gs1.1 adaptive gossip

---

test/pubsub.spec.js
ts/constants.ts
ts/index.ts
ts/pubsub.js

Implements https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#extended-validators
Add extended topic validators and minimal refactoring to properly support it
Integrate scoring for validation (validation begin/reject/ignore), and successful message delivery
`src/pubsub.js` required some refactoring to support this feature. The main reason is that messages should first be checked for `seenCache` entries before running topic validation. Since the `seenCache` is currently on the gossipsub layer, and validation on the pubsub layer, there was some reworking to allow `seenCache` to checked before validation -- namely, moving validation from `_processRpc`, as a pre-step to `_processRpcMessage`, to instead run validation within `_processRpcMessage`. (See …

gs1.1 extended validators

---

ts/constants.ts
ts/heartbeat.ts
ts/index.ts
ts/message/index.ts
ts/message/rpc.proto.ts

Implements https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#prune-backoff-and-peer-exchange prune backoff, not peer exchange
Follows the go-libp2p-pubsub implementation closely.
Extends `ControlPrune` protobuf message and interface to include "peer info"s and backoff. (For now, only backoff is used)
Adds `backoff` Map, a map of maps, indexed by topic, then peer, with a value of a timestamp. If a peer sends a graft for a topic while a backoff entry exists, immediately prune, re-extend the backoff period.
Adds a `heartbeatTicks` counter, will be used for opportunistic grafting in a future PR. Here it's used to clear old backoff entries once every 15 heartbeats.
Adds a `_makePrune` `ControlPrune` constructor. For now, the PX section is not there.

gs1.1 pruning backoff

---

ts/heartbeat.ts

Implements https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#opportunistic-grafting
Depends on #95 
Follows go-libp2p-pubsub implementation
Only one block of code in heartbeat added

gs1.1 opportunistic grafting

---

ts/index.ts
ts/pubsub.js

Add `_acceptFrom` which can be used to graylist peers (will overridden for gs1.1)
Due to the control flow, required to either compute `_acceptFrom` in subclass to determine any further processing (eg: whether to process the control message), OR change the signature of `_processRpc` to return whether or not to continue processing.

feat: add _acceptFrom

---

ts/heartbeat.ts
ts/index.ts

Implements https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#explicit-peering-agreements
Follows the go-libp2p-pubsub implementation closely

gs1.1 direct connect

---

ts/heartbeat.ts
ts/index.ts

Implements https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#spam-protection-measures IWANT and IHAVE limiting
Closely follows go-libp2p-pubsub impl

gs1.1: feat: track ihave/iwant counts

---

ts/index.ts

We should check a peer's score against the publishThreshold even if they are a floodsub peer.
This was missed in integrating the scoring into gossipsub.
Caught looking at go-libp2p-pubsub implementaiton

gs1.1: use publishThreshold for floodsub fallback peers

---

test/peerScore.spec.js
test/tracer.spec.js
test/utils/index.js
test/utils/makeTestMessage.js
ts/heartbeat.ts
ts/index.ts
ts/tracer.ts

Implements https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#spam-protection-measures bullet point 4
Follows go-libp2p-pubsub implementation closely
Suffers from issues related to #105 
eg: in cases where a peer has signaled that they IHAVE a message, we send a IWANT, they send the message, but don't include a signature on a message when we have strict signing, the peer should be penalized twice, once for the invalid message, and once more if they fail to deliver on their promise to send the IWANTed message.
Right now, they only get the first penalty, from the invalid message.

feat: add iwant request tracking

---

ts/index.ts

@jacobheun discovered this bug where if we're connected to a subscriber before the mesh is formed, we don't send them messages.

fix: connected with a subscriber before a mesh is created should send

---

test/2-nodes.spec.js
test/gossip.spec.js
ts/getGossipPeers.ts
ts/heartbeat.ts
ts/index.ts
ts/pubsub.js

Replace many uses of `PeerStreams` with `string` peer id as the primary/sole peer identifier
- internal maps, use string peer id where possible
- internal methods, use string peer id where possible
- only use `peerStreams` when the `peerStreams.protocol` or `peerStreams.write` is needed.
In all cases, the variable name `id` is used to refer to a string peer id.
In a separate PR, we might consider renaming this variable to `p` to more closely conform to the go-libp2p-pubsub implementation.

gs1.1: use string peer id consistently

---

test/peerScore.spec.js
test/pubsub.spec.js
ts/constants.ts
ts/index.ts
ts/score/peerScore.ts
ts/tracer.ts

Implements https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#spam-protection-measures final bullet point
Following the resolution to #105 , we now have a "reason" to reject messages.
This is a slight refactor of `PeerScore#rejectMessage` and `IWantTracer#rejectMessage` to align with go-libp2p-pubsub behavior.
- `rejectMessage` now accepts reason parameter
- `PeerScore#ignoreMessage` removed in favor of reusing `rejectMessage`

gs1.1: feat: add invalid message spam protection

---

ts/heartbeat.ts
ts/index.ts

Add `GossipsubD*` constants as configurable options. Defaults to the contant value, can be overwritten for testing or other purposes.

gs1.1: configurable overlay params

---

package.json

Certified AddressBook got merged. Updated the dependency as the branch is being deleted

chore: use libp2p@0.29 branch

---

README.md
benchmarks/benchmarks.js
package.json
test/2-nodes.spec.js
test/emit-self.spec.js
test/floodsub.spec.js
test/gossip-incoming.spec.js
test/gossip.js
test/messageCache.spec.js
test/multiple-nodes.spec.js
test/pubsub.spec.js
ts/message/index.ts
ts/peer.ts
ts/pubsub.js

All uses of node Buffers have been replaced with Uint8Arrays
Depends on:
BREAKING CHANGES:
- The `.data` and `.seq` properties of messages used to be node Buffers, now they are Uint8Arrays
- All deps of this module now use Uint8Arrays instead of Buffers

fix: replace node buffers with uint8arrays

---

test/pubsub.spec.js
ts/pubsub.js

Previously, we would process any messages we received, even messages in unsubbed topics.

gs1.1: chore: ignore messages from unsubbed topics

---

test/pubsub.spec.js
ts/index.ts
ts/pubsub.js

Remove separate `_publishFrom` function, instead use `_publish`.
Instead of having separate functions for messages published from self vs from others, consolidate all publish functionality into a single `_publish` function. This allows us to remove duplicated code. It also more closely follows the go-libp2p-gossipsub implementation.

chore: consolidate publish functionality

---

.aegir.js
README.md
benchmarks/benchmarks.js
package.json
test/2-nodes.spec.js
test/emit-self.spec.js
test/floodsub.spec.js
test/gossip-incoming.spec.js
test/messageCache.spec.js
test/multiple-nodes.spec.js
test/pubsub.spec.js
ts/message/index.ts
ts/peerStreams.ts
ts/pubsub.js

Pick commit from #118 
Note: the signed peer records side of things is still using Buffers. This should be fixed in a follow up PR as it needs also to be updated in libp2p@0.29 branch

fix: pick uintarrays commit

---

package.json
test/go-gossipsub.js
test/go-gossipsub.spec.js
test/node.js
test/utils/create-gossipsub.js
ts/index.ts

Add go gossipsub tests from: https://github.com/libp2p/go-libp2p-pubsub/blob/master/gossipsub_test.go
A few irrelevant tests have been left out.
A few bugs have been found in the course of running these tests, see #115
A few tests are flaky, a few are failing (after #115)

gs1.1: chore: add go gossipsub tests

---

package.json
test/floodsub.spec.js

Updates libp2p interfaces and floodsub
Removed floodsub uneeded tests with multiple messages as they are included in the interface for floodsub

chore: use libp2p-interfaces0.5.1 and libp2p0.29 rc

---

README.md

Updates Readme usage section. Gossipsub constructor now receives a libp2p instace and the options were updated.
I will open an Issue as well for further improvements here. I think we should have some examples on how to use the more complex options like `scoreParams`, `scoreThresholds` and `directPeers`, otherwise people will need to look into the code.

chore: update readme usage

---

README.md
ts/index.ts

+ For eth2, we want to disable message signing options `{signMessages: false, strictSigning: false}`
+ libp2p-interface allows us to do that, refer to https://github.com/libp2p/js-libp2p-interfaces/blob/master/src/pubsub/index.js#L49

Add message signing options

---

package.json
test/2-nodes.spec.js
test/floodsub.spec.js
test/gossip-incoming.spec.js
test/message-cache.spec.js
test/peer-score.spec.js
ts/index.ts
ts/interfaces.ts
ts/message-cache.ts
ts/score/peer-score.ts
ts/tracer.ts
ts/utils/messageIdToString.ts

It is important pointing out that `getMsgId` function might return a Promise per https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/interfaces/src/pubsub/index.js#L479 We were having issues in browser tests thanks to it, so I needed to make it accept promises too.
Also updates uint8arrays

chore: use latest libp2p release

---

ts/heartbeat.ts

**Motivation**
+ This fix the issue in the heartbeat when we want to find new peers better than the median score
+ To get the index in the middle of the sorted list, we want `Math.floor()`

Fix hearbeat tick handler rounding issue

---

ts/constants.ts
ts/heartbeat.ts
ts/index.ts

There are many options currently set by constants.
This is limiting when applications want to override these for
application-specific networks.
Several interesting options are now overridable via the constructor:
- heartbeatInterval
- fanoutTTL
- mcacheLength
- mcacheGossip
- seenTTL
These options are optional with fallback values defaulting to the prior "constant" values.

feat: add more configuration options

---

README.md

As it points to a deprecated repo which itself points to a broken link.

Fix pubsub interface link

---

.aegir.js
package.json
scripts/node-globals.js
test/go-gossipsub.js
test/gossip.spec.js
test/tracer.spec.js
test/utils/index.js
test/utils/make-test-message.js

There's no need to use node buffers, everything is `Uint8Array` compatible now.
Needs the `libp2p-interfaces-compliance-tests` upgrade from https://github.com/ChainSafe/js-libp2p-gossipsub/pull/173 before CI will pass.

chore: remove node buffers

---

test/accept-from.spec.js
test/peer-score.spec.js
ts/constants.ts
ts/index.ts
ts/score/peer-score.ts

**Motivation**
+ In lodestar, it takes 4% of cpu time just to compute peer score
+ Cache peer score if topic stat & peer stat are unchanged for maximum `decayInterval` time period
+ Main consumer of `computeScore()` is `acceptFrom()` function which is called per incoming message. If peer score >= 0 we allow up to 128 messages and 1s not to compute score (this is safe enough considering `grayListThreshold=-16000`
+ Closes #169
Thanks Teku for the work https://github.com/libp2p/jvm-libp2p/pull/184

Cache peer score

---

CHANGELOG.md
package.json
test/2-nodes.spec.js
test/accept-from.spec.js
test/compliance.spec.js
test/floodsub.spec.js
test/go-gossipsub.js
test/heartbeat.spec.js
test/message-cache.spec.js
test/peer-score.spec.js
test/tracer.spec.js
test/utils/create-gossipsub.js
test/utils/index.js
test/utils/msgId.js
ts/index.ts
ts/interfaces.ts
ts/message-cache.ts
ts/score/message-deliveries.ts
ts/score/peer-score.ts
ts/tracer.ts
ts/utils/messageIdToString.ts
ts/utils/time-cache.ts

**Motivation**
+ Gossipsub is designed to have message redundancy, right now we have to calculate 3.97 times per message data in average, in the worse case we calculate 10/11 times per message data
+ Follow other clients to have a cheaper faster message id just for message de-duplication, so we have fast message id and canonical message id
+ Key as the sha256 of the message (fast message id), value as the canonical message id => enhance `SimpleTimeCache` for this
+ Instead of passing `getMsgId()` function to other classes (PeerScore, GossipTracer, MessageCache) in the constructor, just pass message id through method as we always have them in the consumer code which make it simpler (and Lighthouse does this!)
+ Use the new `getCanonicalMessageIdStr()` function in all places …

Fast messsage id cache

---

.github/workflows/release.yml

**Motivation**
+ Fix error in release workflow https://github.com/ChainSafe/js-libp2p-gossipsub/runs/5184299589?check_suite_focus=true
```
[2/4] Fetching packages...
error peer-id@0.16.0: The engine "node" is incompatible with this module. Expected version ">=15.0.0". Got "14.19.0"
error Found incompatible module.
```
+ Use node 16 for release workflow

Use node 16 to for release workflow

---

ts/index.ts

**Motivation**
+ Avoid computing score when it's not really necessary
**Description:**
+ _publish: Only compute score if peer stream has FloodsubID protocol
+ It's not a big improvement with `master` branch since we cache score already
+ There's another `this.score.score(id)` call some lines below but it's ok since we have score cache
Close #188

_publish: Only compute score if peer stream has FloodsubID protocol

---

package.json
ts/get-gossip-peers.ts
ts/heartbeat.ts
ts/index.ts
ts/message-cache.ts
ts/score/peer-score.ts
ts/tracer.ts
ts/utils/create-gossip-rpc.ts
ts/utils/shuffle.ts
ts/utils/time-cache.ts

JSDocs types are a legacy item from pre-Typescript implementation. Remove since they provide no additional information and can be out of sync

Remove redundant JSDocs

---

ts/constants.ts

In the go implementation of gossipsub, libp2p keeps a 2 minute long cache of recently seen pubsub messages so that the node won't forward on duplicate messages.  In the JS implementation the default seen cache ttl is only 30 seconds.  We have seen issues with duplicate pubsub messages (see https://github.com/libp2p/js-libp2p/issues/1043) and think this shorter cache ttl may be part of the problem.  In any case it would be good for the default behavior to be consistent between the javascript and go implementation

chore: increase the default for seenTTL to match that of go-libp2p

---

ts/index.ts

**Motivation**
+ We use "msg.from" in "_publish" method, however it's only available in "StrictSign" signature policy (lodestar/eth2 uses "StrictNoSign") https://github.com/libp2p/js-libp2p-interfaces/blob/libp2p-interfaces%404.0.4/packages/interfaces/src/pubsub/index.js#L637
+ Use "receivedFrom" which is always available https://github.com/libp2p/js-libp2p-interfaces/blob/libp2p-interfaces%404.0.4/packages/interfaces/src/pubsub/index.js#L687

Fix floodPublish

---

test/go-gossipsub.ts

**Motivation**
+ Reenable go-gossipsub tests
Closes #178 #183

Reenable go-gossipsub tests

---

ts/score/peer-score.ts

**Motivation**
+ Part of the effort to investigate why P3 is applied a lot to peers
+ Do not apply P3 penalty if peers are pruned from topic mesh (double checked with rust-libp2p)

Do not apply P3 penalty if peers are pruned from topic mesh

---

ts/index.ts
ts/metrics.ts
ts/score/peer-score.ts

**Motivation**
To investigate how p3 and p7 affect the final gossip score in lodestar

More metrics for p3 and p7

---

ts/index.ts

**Motivation**
+ Spec:
```
If the message is valid, was not published by the router itself, and has not been previously seen, the router will forward the message. First, it will forward the message to every peer in peers.floodsub[topic] for backwards-compatibility with floodsub. Next, it will forward the message to every peer in its local gossipsub topic mesh, contained in mesh[topic].
```
+ Fix "test mixed gossipsub" in go-gossipsub test
+ Maintain floodsub peers in a set
+ Handle it in "onConnect", "onDisconnect"
+ Use it when selecting peers to forward/publish

Forward messages to floodsub peers

---

ts/index.ts

**Motivation**
Messages are ignored and peer gets penalized
In  `validateReceivedMessage`, result should include `msgId` when topic validator returns 'IGNORE`

Add missing msgId in validateReceivedMessage

---

test/tracer.spec.ts
ts/index.ts
ts/tracer.ts

**Motivation**
Allow lodestar to customize GossipsubIWantFollowupTime

GossipsubIWantFollowupTime as a param

---

ts/metrics.ts
ts/score/peer-score.ts

Add more buckets in parameters we have to fine tune to have sufficient data to choose the right values.
For `duplicateMsgDeliveryDelay` remove the topic label to reduce total number of metrics and use a simple counter `duplicateMsgLateDelivery` by topic instead.

Increase resolution of delay metrics

---

ts/constants.ts
ts/index.ts
ts/metrics.ts
ts/tracer.ts

**Motivation**
+ In lodestar, some metrics have MeshMessageDeliveriesWindow as 0 so we have to filter that out
https://github.com/ChainSafe/lodestar/blob/d8ec024ee3fb3ea170a0519a907da32454cdb49f/packages/lodestar/src/network/gossip/scoringParameters.ts#L262
+ Fix gossipsubIWantFollowupTime for metric
+ Fix tracer prune()

Fix minMeshMessageDeliveriesWindow

---

CHANGELOG.md
package.json

**Motivation**
As a preparation to merge new gossipsub implementation #206

Release 0.13.2

---

ts/index.ts

**Motivation**
The call of `validateToRawMessage` may take some time so we want to check for duplicate messages first (given n mesh peers, there are up to n-1 messages are duplicated)

validateReceivedMessage: check duplicate message first

---

ts/index.ts

`this.metrics?.onMsgRecvPreValidation(rpcMsg.topic)` was called in both `handleReceivedMessage and validateReceivedMessage`

Remove duplicate record of msgReceivedPreValidation metric

---

ts/index.ts
ts/metrics.ts
ts/utils/create-gossip-rpc.ts

Metrics show that every RPC message we sent has a control in it, while only 0.02 received messages have a control. As shown with
```
rate(gossipsub_rpc_sent_control_total[$__rate_interval])
/
rate(gossipsub_rpc_sent_count_total[$__rate_interval])
```
The cause is that the control object is always created even when not necessary.
- Create control object only when necessary
- Register control message when at least one array has at least one element

Fix rpc.control metrics and reduce object creation

---

test/utils/create-gossipsub.ts

**Motivation**
In `connectSome()` function, it does not check for duplicate, a peer may connect to less than the specified `"num"` peers
Maintain `candidatePeers` array and do the random on its key.
Close #240

Fix connectSome test util

---

package.json
src/message/index.ts

While upgrading libp2p and gossipsub in lodestar, it seems we use certain useful things not exported from the root.
Add exports of metrics, message, score, and types for downstream users (like lodestar)

feat: add subpath exports

---

src/index.ts

**Motivation**
+ Correct opportunistic graft.
+ Opportunistic graft happens once every 60 heartbeat, it's used to graft better peers to gradually improve the score of mesh peers
+ We want to graft peers that's not in the mesh, not peers that are already in the mesh

fix: opportunistic graft

---

package.json

without typesVersions, subpath exports' types are not found

fix: fix subpath exports

---

src/index.ts

**Motivation**
+ Fix the way we find more outbound peers during heartbeat
+ Add the condition to find random outbound peers
+ Refer to https://github.com/libp2p/rust-libp2p/blob/fcc987e0f6dd82d0f702acd8b819b4f99a9fb26a/protocols/gossipsub/src/behaviour.rs#L2303

fix: finding outbound peers in heartbeat

---

src/index.ts
src/message-cache.ts
src/tracer.ts
src/types.ts
src/utils/messageIdToString.ts
test/message-cache.spec.ts
test/tracer.spec.ts

**Motivation**
- Lodestar would like to use `Buffer.from` to convert Uint8Array message id to string as it's more efficient as found in https://github.com/ChainSafe/lodestar/issues/3446
- Provide `msgIdToStrFn` option so that application can provide its own implementation
- Closes #269

feat: add msgIdToStrFn option

---

src/index.ts
src/message-cache.ts
src/types.ts
src/utils/messageIdToString.ts
test/message-cache.spec.ts

**Motivation**
- `messageIdFromString()` is not cheap, it takes 1.64 % of cpu time as in one of lodestar beacon node
- we always have Uint8Array message id in all of our flows, we convert to string and we have to convert it back which is a redundancy
- `mcache`: we receive string msgId in `put()`, convert it to Uint8Array to cache and convert it to string again in `shift()` which is another redundancy
- Introduce MessageId `msgId: Uint8Array; msgIdStr: MsgIdStr` with the convention
- msgId: Uint8Array
- msgIdStr: string representation of msgId
- messageId: new MessageId type containing both msgId and msgIdStr
- Cache MessageId in mcache
- remove `messageIdFromString()` completely
- Part of #271
**Memory cost**
- An mcache of 5000 items takes 1MB more, 20000 items take 4MB …

feat: remove messageIdFromString

---

src/index.ts
src/message-cache.ts
test/message-cache.spec.ts

**Motivation**
- when getting gossip message ids, we should loop through mcache history 1 time
- we should only gossip validated messages
- Loop through mcache history 1 time for all topics
- when `asyncValidation` option is undefined or false, messages are consider validated
- when publishing messages, they are considered validated
Closes #271
TODO: wait for https://github.com/ChainSafe/js-libp2p-gossipsub/pull/274

fix: only gossip validated messages

---

src/index.ts
test/signature-policy.spec.ts

#294 only fixed half of the issue,  forwarding no-sign messages.
This PR fixes publishing of no-sign messages.
Also adds unit tests to ensure publish and forward of sign and no-sign messages works.

fix: allow publish of no-sign messages

---

package.json
src/index.ts
src/score/peer-score.ts
src/stream.ts
test/2-nodes.spec.ts
test/e2e/go-gossipsub.spec.ts
test/gossip.spec.ts
test/signature-policy.spec.ts
test/utils/create-pubsub.ts
test/utils/events.ts

The ovararching problem with our previous approach is that we're too carefree about managing streams for this protocol.
Specific problems include:
- creating multiple duplicate outbound streams.
- relying solely on a topology to trigger an outbound stream.
Creation and tracking of new streams is tweaked:
- Add an outbound stream queue
This used to ensure that outbound streams are created sequentially.
This stops multiple duplicate streams from being created for a single peer.
- Attempt to create an outbound stream when an inbound stream is created.
This allows us to connect to peers that haven't yet been registered by the topology but want to connect to us.
- Remove `PeerStreams` usage in favor of managing inbound/outbound streams separately
`PeerStreams` works, but obscures some …

feat: tweak stream handling

---

src/index.ts
test/gossip.spec.ts

The registrar defaults to only allowing 1x inbound and 1x outbound stream per protocol so allow configuring more than that.
I've plucked some defaults out of the air, these will need tuning to make sure they're not too restrictive or permissive.

feat: allow configuring stream limits

---

package.json
src/index.ts
src/stream.ts

**Motivation**
- `it-length-prefixed` yields no-copy data, it should help improve performance
- Migrate to `it-length-prefixed` 8.0.2
- Remove the `BufferList` assumption since `it-length-prefixed` yields Uint8ArrayList consistently

chore: migrate to it-length-prefixed 8.0.2

---

package.json

**Motivation**
- Some libp2p dependencies have breaking changes but were published as hot fix so got build error in this repo
- Freeze dependencies in this version
- Will use updated dependencies based on `js-libp2p` release

fix: freeze libp2p dependencies to get through build errors

---

src/index.ts
src/stream.ts

**Motivation**
- The `pushable` inside `Outbound` stream keeps some internal buffers inside, we need to clear them when closing the `OutboundStream` or it becomes a memory leak if the raw stream is also closed
- End the `pushable` by calling `return()` method when closing outbound stram - it's similar to `end()` but also clearing the internal buffers inside the `pushable`
- Track the inbound/outbound streams in the metrics

fix: handle closing outbound stream

---

test/message-cache.spec.ts
ts/index.ts
ts/message-cache.ts

**Motivation**
- See https://github.com/ChainSafe/lodestar/issues/4412#issuecomment-1214947600
- Similar fix to #277 but we want to make a hot fix to 0.14.x
- only gossip validated messages
- for applications that don't use `asyncValidation`, the message is validated once it put in the cache

feat: only gossip validated messages

---

package.json
src/index.ts

**Motivation**
See #331 
- Fix the condition to skip the heartbeat, right now it looks like we skip if heartbeat runs too fast
- The result is like
Closes #331

fix: skip heartbeat only if it's close to the next heartbeat

---

src/index.ts
src/stream.ts

- See https://github.com/ChainSafe/js-libp2p-gossipsub/issues/321
Add option `maxOutboundBufferSize` to bound the max size of the underlying FIFO queue in OutboundStream.
Closes https://github.com/ChainSafe/js-libp2p-gossipsub/issues/321

feat: add option to limit OutboundStream buffer size

---

src/index.ts

In #325 , pushing an rpc thru the outbound stream can now throw.
This error should be caught to avoid interrupting publishing and forwarding messages.

fix: catch errored push of rpc

---

package.json

As far as I can see this is only used in an interface so the only change needed is to the `package.json` file.

fix: update @multiformats/multiaddr to 11.0.0

---

test/utils/events.ts

The `Events` type has to extend `{ [s: string]: any }`. Hopefully one day TS will ship a typed `EventEmitter` and this won't be necessary any more.
Fixes a type error:
```
[10:45:49] tsc [started]
test/utils/events.ts:64:25 - error TS2344: Type 'Events' does not satisfy the constraint '{ [s: string]: any; }'.
64   emitter: EventEmitter<Events>,
~~~~~~
test/utils/events.ts:63:35
63 export const awaitEvents = async <Events = GossipsubEvents>(
~~~~~~~~~~~~~~~~~~~~~~~~
This type parameter might need an `extends { [s: string]: any; }` constraint.
Found 1 error in test/utils/events.ts:64
```

fix: update event type to extend `{ [s: string]: any }`

---

package.json
tsconfig.json

- There is build issue
```
Error: R] No matching export in "dist/src/message/rpc.cjs" for import "default"
dist/src/message/rpc.js:1:7:
1 │ import cjs from "./rpc.cjs";
```
- root cause is
```
This file is considered to be an ECMAScript module because of the "export" keyword here:
dist/src/message/rpc.cjs:1747:0:
1747 │ export {};
```
During build process, js files are automatically copied to `dist` folder and some how it added 1 extra line at the end
```
export {};
```
and it made `rpc.cjs` file an esm module
- The fix is to copy js files automatically

fix: copy js files to dist manually

---

src/index.ts
src/message-cache.ts
src/metrics.ts

Add metric to track count of messages not validated in the mcache

feat: track mcache not validated count

---

src/index.ts
test/allowedTopics.spec.ts

Allow to provide a whitelist of known topics by the library consumer.
If `allowedTopics` is provided, gossipsub will drop all subscriptions and messages with topics not in the whitelist.

feat: allow only defined list of topics

---

src/index.ts
test/e2e/go-gossipsub.spec.ts

- Fixes typo from https://github.com/ChainSafe/js-libp2p-gossipsub/pull/347 with did not include a negation in a conditional check
@wemeetagain and I believe this logic appears strange and may be flipped. Asked in relevant channels https://discord.com/channels/806902334369824788/942671304530747402/1026542001082077184

fix: flip conditional in piggyback control - typo from #347

---

src/index.ts
src/types.ts
src/utils/time-cache.ts

**Motivation**
- lodestar wants to configure a `fastMsgIdFn` returning a number, see https://github.com/ChainSafe/lodestar/pull/4630/files#diff-9bf17f9668e6c2f27a8beb7f42a7c1a39554a322be5c7843b1def7670a561220R24
Change FastMsgIdFn type accordingly

feat: support FastMsgIdFn returning a number

---

src/index.ts
src/message/decodeRpc.ts
test/decodeRpc.spec.ts

protobuf allows for unlimited list length. Applications can indirectly limit the max length by limiting the max size of incoming RPC packets. However, lists can be filled with tinny elements of 1 byte each that expand to much more. A well crafted RPC can expand x80 or more it's encoded size. By limiting RPC protobuf list length, the multiplier factor is greatly reduced. This approach is adopted by libp2p java and libp2p rust.
The code from `src/message/decodeRpc.ts` is copied from `src/message/rpc.cjs`. Ideally we want to upstream this capability, but this PR should be merged before

feat: limit RPC lists on decode

---

src/message/decodeRpc.ts

[This line](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/master/package.json#L40) copies all files from the `src/messages` folder into `dist` including this `.ts` file, which can then end up getting compiled which depending on your setup fails with:
```
./node_modules/@chainsafe/libp2p-gossipsub/dist/src/message/decodeRpc.ts(1,1): error TS1371: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.
```
The change here is to mark it `import type` as per the error.  An alternative (better?) would be to not copy it into `dist`, either way would solve the problem.

fix: mark import as type

---

src/index.ts
src/stream.ts
test/gossip.spec.ts

If the size is not provided `decode` from `it-length-prefixed` lib applies the ~4mb limit by default:
From npm docs: 
```
maxDataLength: If provided, will not decode messages whose data section exceeds the size specified, if omitted will use the default of 4MB.
```
bellatrix message sizes could be 10MB so this limit needs to be exposed via options so they can be set by lodestar

feat: Add stream option to limit inbound message size

---

src/message/decodeRpc.ts

Added `.js` extension to imported file since compiler gives an error:
`Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './rpc.js'?` 
with `"moduleResolution"` option set to `"NodeNext"`

fix: add .js extension to imported file

---

package.json

Useful when the project use tooling to access the source map.

feat: add `src` folder to package to enable access to source map

---

src/index.ts

**Motivation**
- lodestar, as a consumer of gossipsub, has an issue if we `unsubscribe()` and `subscribe()` the same topic immediately, see https://github.com/ChainSafe/lodestar/issues/4818#issuecomment-1331784399
- it's not an issue in v0.14.1 because `leave()` function is sync instead of async as in master
- Make `leave()` function as sync
part of https://github.com/ChainSafe/lodestar/issues/4818

fix: sync leave() function

---

src/metrics.ts
src/tracer.ts

**Motivation**
- In lodestar, metrics showed there are broken promises but if messages are delivered, they are always on time, i.e. within `gossipsubIWantFollowupMs`
- So I'd like to track messages that are pruned, i.e they're never delivered
- add and track `iwantMessagePruned` metric
part of https://github.com/ChainSafe/lodestar/issues/4818

feat: track pruned messages in tracer

---

src/index.ts
src/metrics.ts
src/tracer.ts

**Motivation**
- To investigate broken promises in https://github.com/ChainSafe/lodestar/issues/4818
- Consider this scenario
- 2 messages have same fastMsgId but different msgIds (collision)
- node sends IWANT control message and add a promise
- message 1 comes and being tracked in fastMsgId
- message 2 (as a response to IWANT) comes, since it has same fastMsgId it's a duplicate we didn't mask as "message delivered" in tracer, and it looks like the other node did not send us the requested messages
- call `tracer. deliverMessage()` in the case of message duplicate
part of https://github.com/ChainSafe/lodestar/issues/4818

fix: tracer to track delivered message if duplicate

---

src/index.ts
src/types.ts
test/gossip.spec.ts

Closes https://github.com/ChainSafe/js-libp2p-gossipsub/issues/367
The default for allowPublishToZeroPeers will be false but a user can optionally call with allowPublishToZeroPeers set to true to suppress InsufficientPeers errors

feat: added allowPublishToZeroPeers as optional param to publish function

---

package-lock.json
package.json
src/score/peer-score-params.ts
src/score/peer-score-thresholds.ts

Related: https://github.com/libp2p/js-libp2p/issues/1269
- deps: bump @libp2p/interfaces
- deps: remove err-code
- chore: replace err-code with CodeError

chore: replace err-code with CodeError

---

src/index.ts
src/metrics.ts

**Motivation**
- libp2p may emit `peer:connect` with a closed connection and we need to handle that, see https://github.com/libp2p/js-libp2p/issues/1565
- Handle that in `onPeerConnected`
- Add a metric to track it
Closes #398

fix: ignore new closed connection

---

src/index.ts
src/metrics.ts

**Motivation**
- There are rpc errors that's not tracked in metrics and it caused missed messages from other peers
- See https://github.com/ChainSafe/js-libp2p-gossipsub/issues/411#issue-1610585138
- Add more logs for rpc message
- Add metrics when handling errors
part of #411
It shows that we really have rpc errors when deploying this branch to a lodestar node

fix: add rpc error metrics

---

src/index.ts

**Motivation**
Lodestar wants to incorporate gossipsub log to its own log files
- According to https://github.com/debug-js/debug#output-streams we should be able to configure per-namespace by overriding the `log` method, however when I tried in lodestar it does not work and we have to use the same log instance
- Change `log` from private to protected so that child class can access and redirect to its own log
Closes #406

feat: make log as protected

---

README.md
package.json

I don't know why we had this.
None of our other repos do this.

chore: remove lead maintainer

---

package.json

Add types to exports in packages.json，to avoid not being able to locate the type definition file when using exports.

fix: add types to exports in packages.json

---

src/metrics.ts

**Motivation**
- On network thread, it takes 3% of cpu time for `gauge.inc()`
- Use single-label metric to improve performance
Closes #426

fix: unbundle 2-label metrics

---

src/index.ts

Resolves #437 
Protocol handling has two components, registering inbound and outbound handlers.
It seems that on gossipsub.stop, we were unregistering the outbound handler but NOT properly unregistering the inbound handler.

fix: unhandle protocol on stop

---

package-lock.json
src/index.ts
src/message-cache.ts
src/metrics.ts
src/score/message-deliveries.ts
src/score/peer-score.ts

**Motivation**
We want to know how long does it take to validate a message with async validation
- Use `firstSeen` field in `MessageDeliveries`
- Add new metrics:
- `asyncValidationDelayFromFirstSeenSec`
- `asyncValidationUnknownFirstSeen`

feat: track async validation delay from first seen

---

src/index.ts

**Motivation**
- In lodestar, passing peer id through thread boundary has to be in string, it has to convert back to a `PeerId` instance at lodestar side and `reportMessageValidationResult` to call `toString()` again, it causes lodestar network thread to waste 2.8% of cpu time
- reportMessageValidationResult to accept peer id string instead, it's a breaking change
part of https://github.com/ChainSafe/lodestar/issues/5604

fix!: reportMessageValidationResult to accept peer id string

---

src/index.ts
src/metrics.ts

**Motivation**
- We use "Unsubscribed" as a churn reason in handlePrune() which is misleading, because it could mean many different thing:
- our peer score is bad => peer prunes us
- it's still in backoff time and we send graft to them => peer prunes us (will open another issue with this)
- peer has too many mesh peers
- peer unsubscribes from topic
- Use the existing "Prune" reason instead

fix: correct metric in handlePrune()

---

src/constants.ts
src/index.ts

**Motivation**
- We want to specify lower backoff time if unsubscribing from a topic as we may resubscribe from that same topic soon
- To follow v1.1 spec of gossipsub https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md
- In `makePrune()`, add a new parameter onUnsubscribe. If it's true specify the backoff time as UnsubscribeBackoff param, update all consumers accordingly
- Also found that we missed adding backoff in this function, double checked with rust-libp2p https://github.com/libp2p/rust-libp2p/blob/f335697573e2688390deeb9708abaeec9f0b9d9f/protocols/gossipsub/src/behaviour.rs#L1116
Closes #249

feat: add UnsubscribeBackoff param

---

src/index.ts
src/metrics.ts

**Motivation**
- I'd like to know how much time to publish a message at gossipsub side
- Add `msgPublishMs` metric and track it
related to #344

feat: track time to publish a message

---

src/metrics.ts

**Motivation**
See https://github.com/ChainSafe/js-libp2p-gossipsub/pull/451#discussion_r1269312699
Track publish time in second as the convention of Prometheus https://prometheus.io/docs/practices/naming/#base-units

fix: track publish time in second

---

src/metrics.ts

- See #461
- It's inconvenient to implement a `MetricsRegister` without the underlying types being exported

fix: export supporting metrics types

---

src/metrics.ts

**Motivation**
- Not able to answer this question: what's the % of IGNORED/REJECTED message validation results for a specific topic
See https://github.com/ChainSafe/lodestar/issues/5853
- Revise the work in https://github.com/ChainSafe/js-libp2p-gossipsub/pull/433/files
- If the label is gossipsub/fixed, we should unbundle to multiple metrics to answer the above question

feat: unbundle fixed-label metrics

---

src/index.ts
src/metrics.ts

**Motivation**
- Found duplicate metrics after merging #460
- There are validation at gossipsub side, and validation at application side that cause the duplicate metric names
- Name the validation in gossipsub "preValidationResult" to distinguish to the validation result coming from application
- Also fix `meshPeerChurnEventsUnknown` metric

fix: revise onPrevalidationResult metrics

---

test/benchmark/protobuf.test.ts

Fix runsFactor in protobuf benchmark. The result on Mac M1:
```
protobuf
✔ decode Attestation message using protobufjs                          3310020 ops/s    302.1130 ns/op   x1.003     395672 runs    120 s
✔ encode Attestation message using protobufjs                          2419082 ops/s    413.3800 ns/op   x1.040     288753 runs    120 s
```

fix: runsFactor in benchmark

---

package-lock.json
package.json
src/index.ts
test/compliance.spec.ts
test/utils/create-pubsub.ts
test/utils/events.ts

The typed `EventEmitter` class from `@libp2p/interface/events` has been renamed `TypedEventEmitter` along with a `TypedEventTarget` interface.
The old name is still exported so it's a backwards compatible change but it will be removed in a future version of `@libp2p/interface` so this change future-proofs `@chainsafe/libp2p-gossipsub` against that upcoming release.

fix: use typed event emitter class

---

src/index.ts
src/score/peer-score.ts
test/peer-score.spec.ts
test/scoreMetrics.spec.ts

Follow up to #473 - makes `PeerScore` use the configured component logger instead of creating a new one.

fix: make peer score use component logger

---

src/index.ts
src/stream.ts
src/types.ts
test/e2e/go-gossipsub.spec.ts
test/floodsub.spec.ts

- Add batch option to publish() api and GossipSub option
- When it's true, encode messages once and send to all peer, ignore cached control messages
cc @wemeetagain 
Closes #344

feat: batch publish

---

src/metrics.ts

See https://github.com/ChainSafe/lodestar/pull/6201 for motivation / rationale

feat: type safe metric labels

---

src/index.ts

Adds an option to allow running gossipsub over transient (e.g. relayed) connections.
By default this is not allowed since transient connections are by design data/time limited and breaching those limits can cause the connection to be closed abruptly, but sometimes people control the relay servers and disable the limits so allow them to use gossipsub over relayed connections if they choose.

feat: add runOnTransientConnection option to pass to registrar

---

package.json
src/stream.ts

AbortableSource is slow because it races promises against every chunk causing extra async work.
It's only really necessary if we're going to pass the source off to another component.
Here we don't do that so it's simpler to just add a listener for the abort event and close the stream.

fix: remove abortable iterator

---

src/index.ts
src/types.ts
test/2-nodes.spec.ts
test/compliance.spec.ts
test/gossip.spec.ts

People continually mistake the `InsufficientPeers` error for something that can be "worked around" by setting `allowPublishToZeroPeers` to true, and they then expect other network nodes to still recieve their messages.
This PR renames the option to `allowPublishToZeroTopicPeers` - this makes it clear(er) that it's not that you don't have any peers, it's that no peers you have are listening on the topic.
It also improves the JSDoc comment on the option and changes the `Error` message from `PublishError.InsufficientPeers` to `PublishError.NoPeersSubscribedToTopic` which (I hope) more accurately describes what's wrong.
BREAKING CHANGE: The `allowPublishToZeroPeers` option has been renamed to `allowPublishToZeroTopicPeers`
Fixes #472

fix!: make PublishError.InsufficientPeers more self-explanatory

---

src/index.ts

**Motivation**
- Lodestar may want to set `floodPublish` as false in the future
- In that case we want to publish at least `mesh_n` peers
see https://github.com/ChainSafe/lodestar/issues/6596#issuecomment-2021834289

feat: publish at least mesh_n peers

---

package-lock.json
package.json
src/index.ts

The latest libp2p release allows services to declare their capabilities (what they provide to the node) and their dependencies (the capabilities they require other services to provide for the config to be "valid").
Adds the `serviceCapabilities` symbol property that says Gossipsub provides the `@libp2p/pubsub` capability and also the `serviceDependencies` symbol property that says it depends on some service providing the `@libp2p/identify` capability - this is required because Gossipsub uses network topologies to discover peers which requires the Identify protocol.

feat: add service capabilities and dependencies definition

---

.github/workflows/main.yml
src/index.ts

`CustomEvent` is [global as of Node.js 18.7.0](https://nodejs.org/docs/latest/api/globals.html#customevent) and the polyfill will be removed in `libp2p@2.x.x` so remove the import here for forwards compatibility with the js-libp2p monorepo.

fix: remove CustomEvent import

---

src/config.ts
src/index.ts

feat: add `gossipFactor` parameter to `GossipsubOpts`
