README.md, package.json
Updated the repo name as defined in the usage for installing the module.
Also added a badge for `made by ChainSafe`.
It would be great that you release an initial version of this module in `npm` after this commit.
=> chore: update repo data

CHANGELOG.md, package.json
@wemeetagain please add the beta tag as you did for the last one
=> chore: release version v0.2.0

package.json
The [package-table](https://www.npmjs.com/package/package-table) package needs this to create a well-formed package table for [libp2p/js-libp2p#packages](https://github.com/libp2p/js-libp2p#packages)
=> chore: add lead maintainer property

.gitignore, test/2-nodes.spec.js, ts/index.ts
Added static member for allowing multicodec to be required from Gossipsub
=> fix: add static member for multicodec

ts/heartbeat.ts, ts/index.ts, ts/interfaces.ts
Miscellaneous fixes found in the course of writing tests
=> gs1.1: chore: misc fixes

ts/index.ts
~~Depends on #120~~
Several significant issues:
- `!iwant || !ihave || !prune`
- we were never:
- responding to ihave messages (with iwants)
- responding to iwant messages (with actual messages)
- sending prune messages when we overgrafted with a peer
- This issue has been present since the birth of this library. In a very real sense, it has always been severely broken.
- shortcircuit ihave/iwant handling
- in the `handleIWant` case, this is just an optimization to avoid calculating a peer score when we don't need to
- in the `handleIHave` case, it also does this, but more importantly, stops flood protection from being erroneously triggered on an empty control message. This would cause ihaves to be mosty ignored in practice, as every rpc would count towards ihave tracking.
- call …
=> gs1.1: chore: fix various bugs

ts/index.ts, ts/messageCache.ts
Implements https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#spam-protection-measures bullet 2
Follows go-libp2p-gossipsub implementation closely
=> chore: add gossip retransmission counter

ts/index.ts
Fixes #117 for gossipsub 0.4.x line
=> fix: rpc control messages 0.4.x

ts/index.ts
Fixes #117 for gossipsub 0.5.x line
=> fix: rpc control messages 0.5.x

README.md
=> chore: readme with 1.1 spec

package.json, test/message-cache.spec.js, test/peer-score.spec.js, test/tracer.spec.js, test/utils/index.js, ts/index.ts, ts/interfaces.ts, ts/message-cache.ts, ts/message/index.ts, ts/message/rpc.proto.ts, ts/score/message-deliveries.ts, ts/score/peer-score.ts, ts/tracer.ts, ts/utils/index.ts, ts/utils/messageIdToString.ts
Following libp2p/js-libp2p-interfaces#65 , support Uint8Array message IDs
=> Support Uint8Array message id

benchmarks/benchmarks.js
This PR updates the benchmarks
=> chore: update benchmarks

package.json, test/benchmark/time-cache.test.js, test/time-cache.spec.js, ts/index.ts, ts/utils/time-cache.ts
**Motivation**
+ Need to implement a faster time cache
+ Implement SimpleTimeCache
+ The benchmark test shows that it's 4x faster than the current npm TimeCache
Close #168
=> Implement SimpleTimeCache

package.json
**Motivation**
Use libp2p-gossipsub 0.12.1 and libp2p 0.35.6 in lodestar
Closes #180
=> Migrate to @types/debug 4.1.7

.prettierignore, ts/message/rpc.d.ts, ts/message/rpc.js
PR https://github.com/ChainSafe/js-libp2p-gossipsub/pull/202 formated auto-generated files.
- Prettier ignore them
- Re-generate
=> Don't format the auto-generated protobuf files

.eslintrc.js, ts/index.ts, ts/message-cache.ts, ts/score/compute-score.ts, ts/score/peer-score.ts, ts/score/peer-stats.ts, ts/tracer.ts
**Motivation**
Found a missing `await` in `if` statement
Add 'strict-boolean-expression` to detect that at compile time
=> Apply strict-boolean-expression eslint rule

test/2-nodes.spec.ts, test/gossip-incoming.spec.ts
=> Fix shouldNotHappen handler

.github/workflows/main.yml, .github/workflows/semantic-pr.yml
=> chore: add missing release token

test/benchmark/protobuf.test.ts
**Motivation**
- Track the performance of protobuf in libp2p-gossipsub
=> chore: benchmark protobuf

.github/workflows/release.yml, CHANGELOG.md, package.json
**Motivation**
- Release 0.14.1 as a hot fix for lodestar
- See https://github.com/ChainSafe/lodestar/issues/4412
=> feat: release 0.14.1

src/index.ts
While the change:multiaddrs listener was a nice idea (we want to know when a peer's IP address changes), in practice it is unnecessary and actually detrimental.
Unnecessary because IP changes will be handled by establishment / closure of streams.
Detrimental because peers can be penalized by announcing their lan IP address which may be the same as another peer. Only a peer _that is actually connected on the same IP address_ should be penalized.
=> fix: remove change:multiaddrs listener

README.md
This PR simply fixes the code example provided by the readme.
=> chore: update readme code example to new API.

package-lock.json, package.json
bump @libp2p/interface-connection to 4.0.0
bump @multiformats/multiaddr to 12.0.0
=> chore(deps): bump @libp2p/interface-connection to 4.0.0

README.md
This will bring the example [up to speed](https://github.com/libp2p/js-libp2p/blob/master/examples/pubsub/1.js).
=> chore: Update README.md usage example

src/index.ts, src/metrics.ts
**Motivation**
- To track backoff time for connected peers
- Add respective metric
Closes #442
=> chore: track backoff time for connected peers
